const Cards = [
  {
    id: 1,
    value: 14,
    suit: 'Pikes',
    name: 'Ace',
    assets_black: 'assets/Cards/black/Pikes_A_black.png',
    assets_white: 'assets/Cards/white/Pikes_A_white.png',
  },
  {
    id: 2,
    value: 13,
    suit: 'Pikes',
    name: 'King',
    assets_black: 'assets/Cards/black/Pikes_King_black.png',
    assets_white: 'assets/Cards/white/Pikes_King_white.png',
  },
  {
    id: 3,
    value: 12,
    suit: 'Pikes',
    name: 'Queen',
    assets_black: 'assets/Cards/black/Pikes_Queen_black.png',
    assets_white: 'assets/Cards/white/Pikes_Queen_white.png',
  },
  {
    id: 4,
    value: 11,
    suit: 'Pikes',
    name: 'Jack',
    assets_black: 'assets/Cards/black/Pikes_Jack_black.png',
    assets_white: 'assets/Cards/white/Pikes_Jack_white.png',
  },
  {
    id: 5,
    value: 10,
    suit: 'Pikes',
    name: 'Ten',
    assets_black: 'assets/Cards/black/Pikes_10_black.png',
    assets_white: 'assets/Cards/white/Pikes_10_white.png',
  },
  {
    id: 6,
    value: 9,
    suit: 'Pikes',
    name: 'Nine',
    assets_black: 'assets/Cards/black/Pikes_9_black.png',
    assets_white: 'assets/Cards/white/Pikes_9_white.png',
  },
  {
    id: 7,
    value: 8,
    suit: 'Pikes',
    name: 'Eight',
    assets_black: 'assets/Cards/black/Pikes_8_black.png',
    assets_white: 'assets/Cards/white/Pikes_8_white.png',
  },
  {
    id: 8,
    value: 7,
    suit: 'Pikes',
    name: 'Seven',
    assets_black: 'assets/Cards/black/Pikes_7_black.png',
    assets_white: 'assets/Cards/white/Pikes_7_white.png',
  },
  {
    id: 9,
    value: 6,
    suit: 'Pikes',
    name: 'Six',
    assets_black: 'assets/Cards/black/Pikes_6_black.png',
    assets_white: 'assets/Cards/white/Pikes_6_white.png',
  },
  {
    id: 10,
    value: 5,
    suit: 'Pikes',
    name: 'Five',
    assets_black: 'assets/Cards/black/Pikes_5_black.png',
    assets_white: 'assets/Cards/white/Pikes_5_white.png',
  },
  {
    id: 11,
    value: 4,
    suit: 'Pikes',
    name: 'Four',
    assets_black: 'assets/Cards/black/Pikes_4_black.png',
    assets_white: 'assets/Cards/white/Pikes_4_white.png',
  },
  {
    id: 12,
    value: 3,
    suit: 'Pikes',
    name: 'Three',
    assets_black: 'assets/Cards/black/Pikes_3_black.png',
    assets_white: 'assets/Cards/white/Pikes_3_white.png',
  },
  {
    id: 13,
    value: 2,
    suit: 'Pikes',
    name: 'Two',
    assets_black: 'assets/Cards/black/Pikes_2_black.png',
    assets_white: 'assets/Cards/white/Pikes_2_white.png',
  },
  {
    id: 14,
    value: 14,
    suit: 'Hearts',
    name: 'Ace',
    assets_black: 'assets/Cards/black/Hearts_A_black.png',
    assets_white: 'assets/Cards/white/Hearts_A_white.png',
  },
  {
    id: 15,
    value: 13,
    suit: 'Hearts',
    name: 'King',
    assets_black: 'assets/Cards/black/Hearts_King_black.png',
    assets_white: 'assets/Cards/white/Hearts_King_white.png',
  },
  {
    id: 16,
    value: 12,
    suit: 'Hearts',
    name: 'Queen',
    assets_black: 'assets/Cards/black/Hearts_Queen_black.png',
    assets_white: 'assets/Cards/white/Hearts_Queen_white.png',
  },
  {
    id: 17,
    value: 11,
    suit: 'Hearts',
    name: 'Jack',
    assets_black: 'assets/Cards/black/Hearts_Jack_black.png',
    assets_white: 'assets/Cards/white/Hearts_Jack_white.png',
  },
  {
    id: 18,
    value: 10,
    suit: 'Hearts',
    name: 'Ten',
    assets_black: 'assets/Cards/black/Hearts_10_black.png',
    assets_white: 'assets/Cards/white/Hearts_10_white.png',
  },
  {
    id: 19,
    value: 9,
    suit: 'Hearts',
    name: 'Nine',
    assets_black: 'assets/Cards/black/Hearts_9_black.png',
    assets_white: 'assets/Cards/white/Hearts_9_white.png',
  },
  {
    id: 20,
    value: 8,
    suit: 'Hearts',
    name: 'Eight',
    assets_black: 'assets/Cards/black/Hearts_8_black.png',
    assets_white: 'assets/Cards/white/Hearts_8_white.png',
  },
  {
    id: 21,
    value: 7,
    suit: 'Hearts',
    name: 'Seven',
    assets_black: 'assets/Cards/black/Hearts_7_black.png',
    assets_white: 'assets/Cards/white/Hearts_7_white.png',
  },
  {
    id: 22,
    value: 6,
    suit: 'Hearts',
    name: 'Six',
    assets_black: 'assets/Cards/black/Hearts_6_black.png',
    assets_white: 'assets/Cards/white/Hearts_6_white.png',
  },
  {
    id: 23,
    value: 5,
    suit: 'Hearts',
    name: 'Five',
    assets_black: 'assets/Cards/black/Hearts_5_black.png',
    assets_white: 'assets/Cards/white/Hearts_5_white.png',
  },
  {
    id: 24,
    value: 4,
    suit: 'Hearts',
    name: 'Four',
    assets_black: 'assets/Cards/black/Hearts_4_black.png',
    assets_white: 'assets/Cards/white/Hearts_4_white.png',
  },
  {
    id: 25,
    value: 3,
    suit: 'Hearts',
    name: 'Three',
    assets_black: 'assets/Cards/black/Hearts_3_black.png',
    assets_white: 'assets/Cards/white/Hearts_3_white.png',
  },
  {
    id: 26,
    value: 2,
    suit: 'Hearts',
    name: 'Two',
    assets_black: 'assets/Cards/black/Hearts_2_black.png',
    assets_white: 'assets/Cards/white/Hearts_2_white.png',
  },
  {
    id: 27,
    value: 14,
    suit: 'Clover',
    name: 'Ace',
  },
  {
    id: 28,
    value: 13,
    suit: 'Clover',
    name: 'King',
  },
  {
    id: 29,
    value: 12,
    suit: 'Clover',
    name: 'Queen',
  },
  {
    id: 30,
    value: 11,
    suit: 'Clover',
    name: 'Jack',
  },
  {
    id: 31,
    value: 10,
    suit: 'Clover',
    name: 'Ten',
  },
  {
    id: 32,
    value: 9,
    suit: 'Clover',
    name: 'Nine',
  },
  {
    id: 33,
    value: 8,
    suit: 'Clover',
    name: 'Eight',
  },
  {
    id: 34,
    value: 7,
    suit: 'Clover',
    name: 'Seven',
  },
  {
    id: 35,
    value: 6,
    suit: 'Clover',
    name: 'Six',
  },
  {
    id: 36,
    value: 5,
    suit: 'Clover',
    name: 'Five',
  },
  {
    id: 37,
    value: 4,
    suit: 'Clover',
    name: 'Four',
  },
  {
    id: 38,
    value: 3,
    suit: 'Clover',
    name: 'Three',
  },
  {
    id: 39,
    value: 2,
    suit: 'Clover',
    name: 'Two',
  },
  {
    id: 40,
    value: 14,
    suit: 'Tiles',
    name: 'Ace',
  },
  {
    id: 41,
    value: 13,
    suit: 'Tiles',
    name: 'King',
  },
  {
    id: 42,
    value: 12,
    suit: 'Tiles',
    name: 'Queen',
  },
  {
    id: 43,
    value: 11,
    suit: 'Tiles',
    name: 'Jack',
  },
  {
    id: 44,
    value: 10,
    suit: 'Tiles',
    name: 'Ten',
  },
  {
    id: 45,
    value: 9,
    suit: 'Tiles',
    name: 'Nine',
  },
  {
    id: 46,
    value: 8,
    suit: 'Tiles',
    name: 'Eight',
  },
  {
    id: 47,
    value: 7,
    suit: 'Tiles',
    name: 'Seven',
  },
  {
    id: 48,
    value: 6,
    suit: 'Tiles',
    name: 'Six',
  },
  {
    id: 49,
    value: 5,
    suit: 'Tiles',
    name: 'Five',
  },
  {
    id: 50,
    value: 4,
    suit: 'Tiles',
    name: 'Four',
  },
  {
    id: 51,
    value: 3,
    suit: 'Tiles',
    name: 'Three',
  },
  {
    id: 52,
    value: 2,
    suit: 'Tiles',
    name: 'Two',
  },
];

export default Cards;
